# Autogenerated wrapper script for SuperLU_jll for i686-w64-mingw32
export libsuperlu

using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("SuperLU")
JLLWrappers.@declare_library_product(libsuperlu, "libsuperlu.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        libsuperlu,
        "bin\\libsuperlu.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
